### ISSUE TITLE
FloatingWindow feature requests

### ISSUE THREAD

**Issue by prabirshrestha** [hrsh7th/vim-vital-vs#1]
Looking into adding floating window support in vim-lsp. https://github.com/prabirshrestha/vim-lsp/pull/1033

And seems like few features are missing.

1. support for z-index
2. events for `on_create`, `on_close`. this allows to easily add custom events or autocmd for us
3. borders support
4. Scroll https://github.com/prabirshrestha/vim-lsp/pull/1025

**Comment by hrsh7th** [comment]
I'm now thinking of FloatingWindow...

1. The `VS.Vim.Window.FloatingWindow` as more primitive
- Don't create any buffer but receive it from the user.
- Don't provide maxheight/maxwidth

2. We should introduce `VS.Vim.Window.Widget.*` (the first candidate is `tooltip? hover? info? hint?)
- It supports borders and scroll target.

The `on_create/on_close` is reasonable. I will add it.

**Comment by prabirshrestha** [comment]
I would also vote for making floating window more primitive as possible. I have shared some of my thoughts here. https://github.com/vim-jp/vital.vim/issues/747 and https://github.com/vim-jp/vital.vim/pull/748.

The way I think of if the primitive popup is only to normalize the apis between vim and neovim.

I would then want a PopupManager which is completely different from the primitive popup and is primarily responsible for setting the right height and position.

Similar to how callbag is solving async and callbacks issues, I was separately working on the popup to support it.

I'm ok not removing max/min width because sometimes that can be used to easily create a popups though vim-lsp might not use it as the PopupManager would be in control of the position as well as width/height.

**Comment by hrsh7th** [comment]
1. support for z-index

1. ~~events for on_create, on_close. this allows to easily add custom events or autocmd for us~~
    - Implemented in #3

1. borders support

1. ~~Scroll prabirshrestha/vim-lsp#1025~~
    - Implemented in #3

**Comment by hrsh7th** [comment]
The scroll methods can be used without `VS.Vim.Window.FloatingWindow`.
It was designed as can be used with a Normal window.

**Comment by prabirshrestha** [comment]
Seems like `pos` is not configurable.

I did implement this in my version of popup.vim.
https://github.com/vim-jp/vital.vim/pull/748/files#diff-38ecd4c22c7dc649baefaf3fc2ae524fb39d44a061defae3db905457d5890507R176-R194

**Comment by hrsh7th** [comment]
It's reasonable. I will add it.

I'm dogfooding with FloatingWindow now.

**Comment by hrsh7th** [comment]
> Seems like pos is not configurable.

I've implemented as `origin` option that accepts as same as you implemented one.

**Comment by prabirshrestha** [comment]
Thanks for the impl. Would also need `zindex` support to help with this issue. https://github.com/prabirshrestha/vim-lsp/issues/1049 I'm hoping to have something like `let g:lsp_documentation_popup_zindex = 100`

**Comment by hrsh7th** [comment]
But neovim's floating window has no zIndex option...

IMO, we shouldn't show floating-window as overlapping the completion-menu.

**Comment by prabirshrestha** [comment]
that makes sense. i would prefer not to support z-index for now.

**Comment by hrsh7th** [comment]
I'm considering border & padding.

**Comment by hrsh7th** [comment]
@prabirshrestha I've implemented simple border supports.

We can pass `'border': v:true` to `s:win.open()`.
